UniversityCourseAndResultManagementWebApp/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityCourseAndResultManagementWebApp.Manager;
using UniversityCourseAndResultManagementWebApp.Menager;
using UniversityCourseAndResultManagementWebApp.Models;

namespace UniversityCourseAndResultManagementWebApp.Controllers
{
    public class CourseController : Controller
    {
        TeacherManager aTeacherManager = new TeacherManager();
        CourseManager aCourseManager = new CourseManager();
        public ActionResult Save()
        {
            List<Department> departments = aCourseManager.GetAllDepartments();
            ViewBag.Departments = departments;
            List<Semester> semesters = aCourseManager.GetAllSemesters();
            ViewBag.Semesters = semesters;
            
            return View();
        }
        public ActionResult Assign()
        {
            List<Department> departments = aCourseManager.GetAllDepartments();
            ViewBag.Departments = departments;
            return View();
        }
        public ActionResult ViewCourse()
        {
            List<Department> departments = aCourseManager.GetAllDepartments();
            ViewBag.Departments = departments;
            return View();
        }
        [HttpPost]

        public ActionResult Save(Course aCourse)
        {
            List<Department> departments = aCourseManager.GetAllDepartments();
            ViewBag.Departments = departments;
            List<Semester> semesters = aCourseManager.GetAllSemesters();
            ViewBag.Semesters = semesters;
            if (aCourse.Credit >= 0.5 && aCourse.Credit <= 5)
            {
                ViewBag.Message = aCourseManager.SaveCourse(aCourse);
                return View();
            }
            ViewBag.Message = "Credit cannot be less than 0.5 and more than 5.0 !!";
            return View();
            
        }
        

        [HttpPost]
        public ActionResult Assign(Course aCourse)
        {
            List<Department> departments = aCourseManager.GetAllDepartments();

            ViewBag.Departments = departments;
            //aCourse.RemainingCredit = aCourse.RemainingCredit - aCourse.Credit;
            ViewBag.Message = aCourseManager.SaveCourseAssign(aCourse);
            if (ViewBag.Message == "Course assigned Successfully !!")
             {
                Teacher teacher = aTeacherManager.GetTeacherInfo(aCourse.TeacherId);
                Course course = aCourseManager.GetCourseInfo(aCourse.CourseId);
                aCourse.RemainingCredit = teacher.RemainingCredit - course.Credit;
                aCourseManager.UpdateRemainingCredit(aCourse);
             }
                
            
            return View();
        }

        public JsonResult GetTeachersByDepartmentId(int departmentId)
        {
            List<Teacher> teachers = aTeacherManager.GetTeachersByDepartmentId(departmentId);
            return Json(teachers);
        }
        public JsonResult GetCoursesByDepartmentId(int departmentId)
        {
            List<Course> courses = aTeacherManager.GetCoursesByDepartmentId(departmentId);
            return Json(courses);
        }
        public JsonResult GetTeacherInfo(int teacherId)
        {
            Teacher aTeacher = aTeacherManager.GetTeacherInfo(teacherId);
            return Json(aTeacher);
        }
        public JsonResult GetCourseInfo(int courseId)
        {
            Course aCourse = aCourseManager.GetCourseInfo(courseId);
            return Json(aCourse);
        }
        public JsonResult GetCourseDetailes(int departmentId)
        {
            List<ViewModel> viewModels = aCourseManager.GetCourseDetailes(departmentId);
            return Json(viewModels);
        }
        public ActionResult UnassignCourse()
        {
            return View();
        }
        [HttpPost]
        public ActionResult UnassignCourse(string confirmValue)
        {
            if (confirmValue == "Yes")
            {
                List<Teacher> teachers = aCourseManager.GetTeacherCredit();
                foreach (Teacher teacher in teachers)
                {
                    aCourseManager.UpdateRemainingCr(teacher);
                }
                ViewBag.Message = aCourseManager.UnassignCourses();
            }
            else
            {
                ViewBag.Message = "You clicked NO!";
            }
 
            return View();
        }
	}
}

UniversityCourseAndResultManagementWebApp/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityCourseAndResultManagementWebApp.Manager;
using UniversityCourseAndResultManagementWebApp.Menager;
using UniversityCourseAndResultManagementWebApp.Models;

namespace UniversityCourseAndResultManagementWebApp.Controllers
{
    public class DepartmentController : Controller
    {
        DepartmentManager aDepartmentManager = new DepartmentManager();
        CourseManager aCourseManager = new CourseManager();
        //
        // GET: /Department/
        public ActionResult Save()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Save(Department aDepartment)
        {
            ViewBag.Message = aDepartmentManager.Save(aDepartment);
            return View();
        }
        public ActionResult ViewDepartments ()
        {
            List<Department> departments = aCourseManager.GetAllDepartments();
            ViewBag.Departments = departments;
            return View();
        }
	}
}

UniversityCourseAndResultManagementWebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UniversityCourseAndResultManagementWebApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

UniversityCourseAndResultManagementWebApp/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Owin.Security.Provider;
using UniversityCourseAndResultManagementWebApp.Manager;
using UniversityCourseAndResultManagementWebApp.Menager;
using UniversityCourseAndResultManagementWebApp.Models;

namespace UniversityCourseAndResultManagementWebApp.Controllers
{
    public class StudentController : Controller
    {
        StudentManager aStudentManager = new StudentManager();
        CourseManager aCourseManager = new CourseManager();
        //
        // GET: /Student/
        public ActionResult Register()
        {
            List<Department> departments = aCourseManager.GetAllDepartments();
            ViewBag.Departments = departments;
            return View();
        }
        [HttpPost]
        public ActionResult Register(Student aStudent)
        {
            ViewBag.Message = DateTime.Now.Year.ToString();
            List<Department> departments = aCourseManager.GetAllDepartments();
            ViewBag.Departments = departments;
           
            aStudent.RegistrationNo = GetRegistrtionNo(aStudent);
            ViewBag.Message = aStudentManager.Save(aStudent);
            aStudent.DepartmentName = aStudentManager.GetDeptName(aStudent.DepartmentId);
            ViewBag.Student = aStudent;
            return View();
        }

        private string GetRegistrtionNo(Student aStudent)
        {
            string deptCode = aStudentManager.GetDeptCode(aStudent.DepartmentId);
            var test = Convert.ToDateTime(aStudent.Date);
            int year = test.Year;
            string registrationNo = deptCode + "-" + year;
            string code = aStudentManager.GetNoOfStudents(registrationNo).ToString();
            if (code.Length == 1)
            {
                code = "00" + code;
            }
            else if (code.Length == 2)
            {
                code = "0" + code;
            }
            registrationNo = registrationNo + "-" + code;
            return registrationNo;
            
        }

        public ActionResult SaveResult()
        {
            List<Student> registrationNos = aStudentManager.GetAllRegistrationNo();
            ViewBag.RegistrationNos = registrationNos;
            return View();
        }
        [HttpPost]
        public ActionResult SaveResult(Student aStudent)
        {
            List<Student> registrationNos = aStudentManager.GetAllRegistrationNo();
            aStudent.RegistrationNo = aStudentManager.GetRegNo(aStudent.Id);
            ViewBag.RegistrationNos = registrationNos;
            ViewBag.Message = aStudentManager.SaveResult(aStudent);
            return View();
        }
     

         public JsonResult GetStudentInfo(int id)
        {
            Student student = aStudentManager.GetStudentInfo(id);
            return Json(student);
        }
         public JsonResult GetCoursesByStudentId(int id)
         {
             List<Student> courses = aStudentManager.GetCoursesByRegistrationId(id);
             return Json(courses);
         }
         public ActionResult EnrollCourse()
         {
             List<Student> registrationNos = aStudentManager.GetAllRegistrationNo();
             ViewBag.RegistrationNos = registrationNos;
             return View();
         }
         [HttpPost]
         public ActionResult EnrollCourse(Student aStudent)
         {
             List<Student> registrationNos = aStudentManager.GetAllRegistrationNo();
             ViewBag.RegistrationNos = registrationNos;
             aStudent.RegistrationNo = aStudentManager.GetRegNo(aStudent.Id);
             ViewBag.MEssage = aStudentManager.EnrollCourse(aStudent);
             return View();
         }
         public JsonResult GetCoursesByRegId(int id)
         {
             int departmentId = aStudentManager.GetDeptIdByRegId(id);
             List<Student> courses = aStudentManager.GetCoursesByDeptId(departmentId);
             return Json(courses);
         }
         public JsonResult GetStudentInfoByRegNo(int id)
         {
             Student student = aStudentManager.GetStudentInfoByRegNo(id);
             return Json(student);
         }
       
    }
}

UniversityCourseAndResultManagementWebApp/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityCourseAndResultManagementWebApp.Manager;
using UniversityCourseAndResultManagementWebApp.Menager;
using UniversityCourseAndResultManagementWebApp.Models;

namespace UniversityCourseAndResultManagementWebApp.Controllers
{
    public class TeacherController : Controller
    {
        TeacherManager aTeacherManager = new TeacherManager();
        CourseManager aCourseManager = new CourseManager();
        public ActionResult Save()
        {
            List<Department> departments = aCourseManager.GetAllDepartments();
            ViewBag.Departments = departments;
            List<Designation> designations = aTeacherManager.GetAllDesignations();
            ViewBag.Designation = designations;
            return View();
        }
        [HttpPost]
        public ActionResult Save(Teacher aTeacher)
        {
            List<Department> departments = aCourseManager.GetAllDepartments();
            ViewBag.Departments = departments;
            List<Designation> designations = aTeacherManager.GetAllDesignations();
            ViewBag.Designation = designations;
            if (aTeacher.CreditLimit >= 0)
            {
                ViewBag.Message = aTeacherManager.SaveTeacher(aTeacher);
                return View();  
            }
            ViewBag.Message = " Credit to be taken field must contain a non-negative value !!";
            return View();

        }
	}
}

UniversityCourseAndResultManagementWebApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

UniversityCourseAndResultManagementWebApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

UniversityCourseAndResultManagementWebApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron" style="text-align: center;font-style: italic">
    @*<p>@Html.ActionLink("Home", "Index", "Home")</p>
    <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
    <p>@Html.ActionLink("Save Department", "Save", "Department")</p>
    <p>@Html.ActionLink("View All Departments", "ViewDepartments", "Department")</p>
    <p>@Html.ActionLink("Save Course", "Save", "Course")</p>
    <p>@Html.ActionLink("Save Teacher", "Save", "Teacher")</p>
    <p>@Html.ActionLink("Course Assign to Teacher", "Assign", "Course")</p>
    <p>@Html.ActionLink("View Course Statics", "ViewCourse", "Course")</p>
    <p>@Html.ActionLink("Register Student", "Register", "Student")</p>
    <p>@Html.ActionLink("Enroll In a Course ", "EnrollCourse", "Student")</p>
    <p>@Html.ActionLink("Save Student Result", "SaveResult", "Student")</p>
    <p>@Html.ActionLink("Unassign All Courses", "UnassignCourse", "Course")</p>

    @*<h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-large">Learn more &raquo;</a></p>*@
</div>

@*<div class="row">
    <div class="col-md-4">
        <ul class="nav navbar-nav">*@
          
        
        @*<h2>Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            @*<p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </div>
    </div>*@